### PR TITLE
wind convention parameters

### PR DESCRIPTION
**Pull request by vincelhx**
oceano / meteo wind

### CODE REVIEW

**Comment by Skealz** [comment]
Maybe, in the config, wind_dir_convention or dir_convention are more explicit ?

**Comment by vincelhx** [comment]
I took advantage of this PR to change a bit the call of `preprocess`

**Comment by vincelhx** [comment]
I added a function to check that incidence range is included in LUT incidence range ; 
in order to prevent user ; if not included, inversion will use wrong inversion angle and so provide wrong wind values

**Comment by vincelhx** [comment]
i also renamed  `model_vv` => `model_co` et `model_vh` =>  `model_cross`

**Pull request merged**
